{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- include "application-collection.render.annotations" (dict "additionalAnnotations" .Values.service.annotations "context" $) | indent 2 }}
  {{- include "application-collection.render.labels" (dict "component" "main" "context" $) | indent 2 }}
  name: {{ include "application-collection.fullName" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- include "application-collection.render.values" (dict "omitKeys" (list "enabled" "annotations" "nodePorts" "ports" "selector") "values" .Values.service) | indent 2 }}
  ports: {{- range $key, $value := .Values.service.ports }}
    {{- if and $key (coalesce $value (get $.Values.containerPorts $key)) }}
    - name: {{ $key }}
      {{- if has $.Values.service.type (list "LoadBalancer" "NodePort") }}
      {{- if not (empty (get $.Values.service.nodePorts $key)) }}
      nodePort: {{ get $.Values.service.nodePorts $key }}
      {{- end }}
      {{- end }}
      port: {{ coalesce $value (get $.Values.containerPorts $key) }}
      {{- if get $.Values.containerPorts $key }}
      targetPort: {{ $key }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector: {{- include "application-collection.labels.match" (dict "additionalLabels" .Values.podTemplates.labels "component" "main" "context" $) | nindent 4 }}
{{- end }}
