apiVersion: v1
kind: Service
metadata:
  {{- include "application-collection.render.annotations" (dict "additionalAnnotations" .Values.headlessService.annotations "context" $) | indent 2 }}
  {{- include "application-collection.render.labels" (dict "component" "main" "context" $) | indent 2 }}
  name: {{ include "application-collection.fullName" (dict "suffix" "headless" "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- include "application-collection.render.values" (dict "omitKeys" (list "enabled" "annotations" "ports" "selector") "values" .Values.headlessService) | indent 2 }}
  ports: {{- range $key, $value := .Values.headlessService.ports }}
    {{- if and $key (coalesce $value (get $.Values.containerPorts $key)) }}
    - name: {{ $key }}
      port: {{ coalesce $value (get $.Values.containerPorts $key) }}
      {{- if get $.Values.containerPorts $key }}
      targetPort: {{ $key }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector: {{- include "application-collection.labels.match" (dict "additionalLabels" .Values.podTemplates.labels "component" "main" "context" $) | nindent 4 }}
