global:
  imagePullSecrets:
  - application-collection
  ollama:
  models:
    pull:
      - "qwen2.5:1.5b"
    insecure: false
specs:
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  defaultModel: "qwen2.5:1.5b"

ingress:
  enabled: false
persistentVolume:
  storageClass: local-path