annotations:
  helm.sh/images: |
    - image: dp.apps.rancher.io/containers/milvus:2.4.6
      name: milvus
apiVersion: v2
appVersion: 2.4.6
dependencies:
- condition: etcd.enabled
  name: etcd
  repository: oci://dp.apps.rancher.io/charts
  tags:
  - etcd
  version: 0.2.7
- condition: minio.enabled
  name: minio
  repository: oci://dp.apps.rancher.io/charts
  tags:
  - minio
  version: 5.2.0
- alias: kafka
  condition: kafka.enabled
  name: apache-kafka
  repository: oci://dp.apps.rancher.io/charts
  tags:
  - kafka
  version: 0.2.0
description: Milvus is a high-performance vector database built for scale. It is used
  by AI applications to organize and search through large amount of unstructured data,
  such as text, images, and multi-modal information.
home: https://apps.rancher.io/applications/milvus
icon: https://raw.githubusercontent.com/milvus-io/docs/master/v1.0.0/assets/milvus_logo.png
keywords:
- milvus
- elastic
- vector
- search
- deploy
kubeVersion: ^1.10.0-0
maintainers:
- name: SUSE LLC
  url: https://www.suse.com
name: milvus
version: 4.2.2
