global:
  imagePullSecrets:
  - application-collection
  namespace: suseai
image:
  registry: dp.apps.rancher.io
  repository: containers/milvus
  tag: 2.4.6
  # repository: ghcr.io/open-webui/open-webui
  # tag: 0.5.10
  pullPolicy: IfNotPresent
cluster:
  enabled: False
standalone:
  persistence:
    persistentVolumeClaim:
      storageClass: local-path
etcd:
  replicaCount: 1
  persistence:
    storageClassName: local-path
minio:
  mode: standalone
  replicas: 1
  rootUser: "admin"
  rootPassword: "adminminio"
  persistence:
    storageClass: local-path
  resources:
    requests:
      memory: 1024Mi
kafka:
  enabled: true
  name: kafka
  replicaCount: 1
  broker:
    enabled: true
  cluster:
    listeners:
      client:
        protocol: 'PLAINTEXT'
      controller:
        protocol: 'PLAINTEXT'
  persistence:
    enabled: true
    annotations: {}
    labels: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: "local-path"