{{- if and .Values.auth.token.enabled (eq .Values.auth.token.type "jwt") (not (tpl .Values.auth.token.existingSecret .)) }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "renderAnnotations" . | indent 2 }}
  {{- include "renderLabels" (dict "component" "main" "context" $) | indent 2 }}
  name: {{ include "fullName" (dict "suffix" "jwt-token" "context" .) }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- $secretName := tpl .Values.auth.token.privateKeyFilename $ }}
  {{ $secretName }}: {{ include "lookupSecret" (dict "default" (genPrivateKey "rsa") "key" $secretName "secret" (include "fullName" (dict "suffix" "jwt-token" "context" .)) "context" $) }}
{{- end }}
