{{- $component := "controller" }}
{{- $scripts := .Files.Glob "scripts/{*,controller/*}.sh" }}
{{- if $scripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "renderAnnotations" . | indent 2 }}
  {{- include "renderLabels" (dict "component" $component "context" $) | indent 2 }}
  name: {{ include "fullName" (dict "suffix" (printf "%s-%s" $component "scripts") "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- range $path, $contents := $scripts }}
  {{ base $path }}: |
    {{- printf "%s" $contents | nindent 4 }}
  {{- end }}
{{- end }}
