{{- $component := "controller" }}
{{- $service := .Values.controller.service }}
{{- $podTemplates := .Values.controller.podTemplates }}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- include "renderAnnotations" (dict "additionalAnnotations" $service.annotations "context" $) | indent 2 }}
  {{- include "renderLabels" (dict "component" $component "context" $) | indent 2 }}
  name: {{ include "fullName" (dict "suffix" $component "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- include "renderValues" (dict "omitKeys" (list "enabled" "annotations" "nodePorts" "ports" "selector") "values" $service) | indent 2 }}
  ports: {{- range $key, $value := $service.ports }}
    {{- if and $key (coalesce $value (get $.Values.containerPorts $key)) }}
    - name: {{ $key }}
      {{- if has $service.type (list "LoadBalancer" "NodePort") }}
      {{- if not (empty (get $service.nodePorts $key)) }}
      nodePort: {{ get $service.nodePorts $key }}
      {{- end }}
      {{- end }}
      port: {{ coalesce $value (get $.Values.containerPorts $key) }}
      {{- if get $.Values.containerPorts $key }}
      targetPort: {{ $key }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector: {{- include "matchLabels" (dict "additionalLabels" $podTemplates.labels "component" $component "context" $) | nindent 4 }}
{{- end }}
