{{- $component := "controller" }}
{{- $headlessService := .Values.controller.headlessService }}
{{- $podTemplates := .Values.controller.podTemplates }}
apiVersion: v1
kind: Service
metadata:
  {{- include "renderAnnotations" (dict "additionalAnnotations" $headlessService.annotations "context" $) | indent 2 }}
  {{- include "renderLabels" (dict "component" $component "context" $) | indent 2 }}
  name: {{ include "fullName" (dict "suffix" (printf "%s-%s" $component "headless") "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- include "renderValues" (dict "omitKeys" (list "enabled" "annotations" "ports" "selector") "values" $headlessService) | indent 2 }}
  ports: {{- range $key, $value := $headlessService.ports }}
    {{- if and $key (coalesce $value (get $.Values.containerPorts $key)) }}
    - name: {{ $key }}
      port: {{ coalesce $value (get $.Values.containerPorts $key) }}
      {{- if get $.Values.containerPorts $key }}
      targetPort: {{ $key }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector: {{- include "matchLabels" (dict "additionalLabels" $podTemplates.labels "component" $component "context" $) | nindent 4 }}
