annotations:
  helm.sh/images: |
    - image: dp.apps.rancher.io/containers/ollama:0.5.7
      name: ollama
    - image: dp.apps.rancher.io/containers/bci-busybox:15.5
      name: bci-busybox
apiVersion: v2
appVersion: 0.5.7
description: Get up and running with Llama 3.2, Mistral, Gemma 2, and other large
  language models.
home: https://apps.rancher.io/applications/ollama
icon: https://ollama.ai/public/ollama.png
keywords:
- ai
- llm
- llama
- mistral
kubeVersion: ^1.16.0-0
maintainers:
- name: SUSE LLC
  url: https://www.suse.com
name: ollama
sources:
- https://github.com/ollama/ollama
type: application
version: 1.4.0
