{{- $configMap := default (include "fullName" (dict "suffix" "cluster" "context" $)) .Values.cluster.clusterConfigMap }}
{{- $clusterID := include "lookupConfigMap" (dict "default" (randAlphaNum 16) "configMap" $configMap "key" .Values.cluster.clusterIDKey "context" $) }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "renderAnnotations" . | indent 2 }}
  {{- include "renderLabels" (dict "component" "cluster" "context" $) | indent 2 }}
  name: {{ include "fullName" (dict "suffix" "cluster" "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{ tpl .Values.cluster.clusterIDKey . }}: |
    {{- tpl $clusterID $ | nindent 4 }}
