{{- if (eq (include "application-collection.render.boolean" (dict "template" .Values.secret.enabled "context" $)) "true") }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "application-collection.render.annotations" . | indent 2 }}
  {{- include "application-collection.render.labels" (dict "component" "main" "context" $) | indent 2 }}
  name: {{ include "application-collection.fullName" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- range $secretName, $secretValue := .Values.secret }}
  {{- if and $secretName (ne $secretName "enabled") $secretValue }}
  {{ tpl $secretName $ }}: {{ include "application-collection.lookup.secret" (dict "default" (tpl $secretValue $) "key" (tpl $secretName $) "context" $) }}
  {{- end }}
  {{- end }}
{{- end }}
