{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "application-collection.render.annotations" (dict "additionalAnnotations" .Values.serviceAccount.annotations "context" $) | indent 2 }}
  {{- include "application-collection.render.labels" (dict "additionalLabels" .Values.serviceAccount.labels "context" $) | indent 2 }}
  name: {{ include "application-collection.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- include "application-collection.render.values" (dict "omitKeys" (list "enabled" "annotations" "labels" "name") "values" .Values.serviceAccount) | indent 0 }}
{{- end }}
