kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: suseai
  namespace: default
spec:
  repo: https://github.com/alessandro-festa/fleet-examples
  branch: main
  paths:
  - suseai/milvus
  - suseai/owui